import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../datamodels/menu_items.dart';
import '../datamodels/restaurant.dart';

class RestaurantNotifier extends StateNotifier<List<Restaurant>> {
  RestaurantNotifier()
      : super([
          Restaurant(
            name: "Mama Eko Kitchen",
            location: "Surulere, Lagos",
            rating: 4.7,
            reviewCount: 320,
            price: 500,
            deliveryTime: "25 - 35 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 269.png",
            openingHours: "9:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Abacha",
                description:
                    "Abacha wey go harvard, wey con get honorary degree from cam...",
                price: 400,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
              MenuItem(
                name: "Abacha",
                description:
                    "Abacha wey go harvard, wey con get honorary degree from cam...",
                price: 400,
                isAvailable: false,
                imageUrl: "asset/images/Frame 26912.png",
              ),
              MenuItem(
                name: "Abacha",
                description:
                    "Abacha wey go harvard, wey con get honorary degree from cam...",
                price: 400,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
              MenuItem(
                name: "Abacha",
                description:
                    "Abacha wey go harvard, wey con get honorary degree from cam...",
                price: 400,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
              MenuItem(
                name: "Abacha",
                description:
                    "Abacha wey go harvard, wey con get honorary degree from cam...",
                price: 400,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
              MenuItem(
                name: "Abacha",
                description:
                    "Abacha wey go harvard, wey con get honorary degree from cam...",
                price: 400,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
            ],
          ),
          Restaurant(
            name: "Taste of Lagos",
            location: "Victoria Island, Lagos",
            rating: 4.9,
            reviewCount: 450,
            price: 1500,
            deliveryTime: "20 - 30 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 26912.png",
            openingHours: "10:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Jollof Rice",
                description: "Delicious jollof rice with a rich tomato flavor.",
                price: 800,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
              MenuItem(
                name: "Pepper Soup",
                description: "Spicy pepper soup with assorted meat.",
                price: 1000,
                isAvailable: false,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
          Restaurant(
            name: "Iya Basira’s Bukka",
            location: "Ikeja, Lagos",
            rating: 4.5,
            reviewCount: 280,
            price: 600,
            deliveryTime: "30 - 40 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 2694.png",
            openingHours: "8:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Pounded Yam & Egusi",
                description:
                    "Soft pounded yam with rich egusi stew and assorted meat.",
                price: 700,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
              MenuItem(
                name: "Amala & Ewedu",
                description: "Smooth amala with ewedu soup and gbegiri.",
                price: 650,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
            ],
          ),
          Restaurant(
            name: "Calabar Kitchen",
            location: "Lekki Phase 1, Lagos",
            rating: 4.8,
            reviewCount: 390,
            price: 1200,
            deliveryTime: "20 - 30 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 2694.png",
            openingHours: "9:30 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Edikang Ikong",
                description:
                    "Traditional Calabar vegetable soup with assorted meat.",
                price: 1000,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
              MenuItem(
                name: "Afang Soup",
                description: "Rich afang soup with periwinkles and fish.",
                price: 1100,
                isAvailable: false,
                imageUrl: "asset/images/Frame 2694.png",
              ),
            ],
          ),
          Restaurant(
            name: "Suya Spot",
            location: "Yaba, Lagos",
            rating: 4.3,
            reviewCount: 150,
            price: 400,
            deliveryTime: "15 - 25 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 2694.png",
            openingHours: "11:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Beef Suya",
                description:
                    "Spicy grilled beef suya with onions and tomatoes.",
                price: 500,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
              MenuItem(
                name: "Chicken Suya",
                description: "Tender chicken suya with a smoky flavor.",
                price: 600,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
          Restaurant(
            name: "The Grill House",
            location: "Ikoyi, Lagos",
            rating: 4.6,
            reviewCount: 500,
            price: 2000,
            deliveryTime: "25 - 35 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 2694.png",
            openingHours: "10:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Grilled Steak",
                description: "Juicy grilled steak with pepper sauce and fries.",
                price: 2500,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
              MenuItem(
                name: "BBQ Ribs",
                description:
                    "Tender BBQ ribs with coleslaw and mashed potatoes.",
                price: 2800,
                isAvailable: false,
                imageUrl: "asset/images/Frame 2694.png",
              ),
            ],
          ),
          Restaurant(
            name: "Aunty Nkechi’s Place",
            location: "Ajah, Lagos",
            rating: 4.4,
            reviewCount: 220,
            price: 550,
            deliveryTime: "30 - 40 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 26912.png",
            openingHours: "8:30 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Ofada Rice & Sauce",
                description: "Local ofada rice with spicy ayamase sauce.",
                price: 600,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
              MenuItem(
                name: "Fish Pepper Soup",
                description: "Spicy fish pepper soup with yam chunks.",
                price: 800,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
          Restaurant(
            name: "Chop & Chill",
            location: "Maryland, Lagos",
            rating: 4.2,
            reviewCount: 180,
            price: 700,
            deliveryTime: "20 - 30 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 269.png",
            openingHours: "9:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Fried Rice & Chicken",
                description: "Flavorful fried rice with grilled chicken.",
                price: 900,
                isAvailable: true,
                imageUrl: "asset/images/Frame 269.png",
              ),
              MenuItem(
                name: "Plantain & Fish",
                description: "Fried plantain with grilled fish and sauce.",
                price: 850,
                isAvailable: false,
                imageUrl: "asset/images/Frame 269.png",
              ),
            ],
          ),
          Restaurant(
            name: "Ewa Agoyin Express",
            location: "Oshodi, Lagos",
            rating: 4.1,
            reviewCount: 130,
            price: 350,
            deliveryTime: "15 - 25 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 2694.png",
            openingHours: "7:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Ewa Agoyin & Bread",
                description:
                    "Mashed beans with spicy agoyin sauce and soft bread.",
                price: 400,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
              MenuItem(
                name: "Boiled Yam & Sauce",
                description: "Boiled yam with spicy palm oil sauce.",
                price: 450,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
            ],
          ),
          Restaurant(
            name: "Spice & Sizzle",
            location: "Gbagada, Lagos",
            rating: 4.5,
            reviewCount: 300,
            price: 800,
            deliveryTime: "25 - 35 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 26912.png",
            openingHours: "9:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Asun",
                description: "Spicy grilled goat meat with peppers and onions.",
                price: 1000,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
              MenuItem(
                name: "Nkwobi",
                description: "Spicy cow foot in palm oil sauce with ugba.",
                price: 1200,
                isAvailable: false,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
          Restaurant(
            name: "The Pasta Place",
            location: "Ikota, Lagos",
            rating: 4.7,
            reviewCount: 410,
            price: 1800,
            deliveryTime: "20 - 30 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 2694.png",
            openingHours: "10:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Spaghetti Bolognese",
                description: "Spaghetti with rich beef bolognese sauce.",
                price: 2000,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
              MenuItem(
                name: "Chicken Alfredo",
                description: "Creamy alfredo pasta with grilled chicken.",
                price: 2200,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
          Restaurant(
            name: "Ogbono Delight",
            location: "Ikorodu, Lagos",
            rating: 4.3,
            reviewCount: 200,
            price: 600,
            deliveryTime: "30 - 40 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 2694.png",
            openingHours: "8:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Ogbono Soup",
                description: "Thick ogbono soup with assorted meat and fish.",
                price: 700,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
              MenuItem(
                name: "Pounded Yam",
                description: "Soft pounded yam to pair with your soup.",
                price: 300,
                isAvailable: true,
                imageUrl: "asset/images/Frame 269.png",
              ),
            ],
          ),
          Restaurant(
            name: "The Shawarma Hub",
            location: "Festac Town, Lagos",
            rating: 4.4,
            reviewCount: 250,
            price: 900,
            deliveryTime: "15 - 25 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 26912.png",
            openingHours: "11:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Chicken Shawarma",
                description: "Juicy chicken shawarma with veggies and sauce.",
                price: 1000,
                isAvailable: true,
                imageUrl: "asset/images/Frame 269.png",
              ),
              MenuItem(
                name: "Beef Shawarma",
                description: "Tender beef shawarma with garlic sauce.",
                price: 1100,
                isAvailable: false,
                imageUrl: "asset/images/Frame 269.png",
              ),
            ],
          ),
          Restaurant(
            name: "Buka 360",
            location: "Mushin, Lagos",
            rating: 4.2,
            reviewCount: 170,
            price: 450,
            deliveryTime: "20 - 30 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 26912.png",
            openingHours: "7:30 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Eba & Vegetable Soup",
                description: "Garri with rich vegetable stew and fish.",
                price: 500,
                isAvailable: true,
                imageUrl: "asset/images/Frame 269.png",
              ),
              MenuItem(
                name: "Beans & Plantain",
                description: "Stewed beans with fried plantain.",
                price: 400,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
          Restaurant(
            name: "The Pizza Joint",
            location: "Magodo, Lagos",
            rating: 4.6,
            reviewCount: 380,
            price: 1500,
            deliveryTime: "25 - 35 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 269.png",
            openingHours: "10:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Pepperoni Pizza",
                description: "Classic pepperoni pizza with mozzarella cheese.",
                price: 1800,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
              MenuItem(
                name: "Margherita Pizza",
                description: "Fresh tomato, basil, and mozzarella pizza.",
                price: 1600,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
          Restaurant(
            name: "Mama Put Corner",
            location: "Agege, Lagos",
            rating: 4.0,
            reviewCount: 120,
            price: 400,
            deliveryTime: "20 - 30 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 269.png",
            openingHours: "7:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "White Rice & Stew",
                description: "White rice with tomato stew and chicken.",
                price: 450,
                isAvailable: true,
                imageUrl: "asset/images/Frame 269.png",
              ),
              MenuItem(
                name: "Moi Moi",
                description: "Steamed bean pudding with fish.",
                price: 300,
                isAvailable: false,
                imageUrl: "asset/images/Frame 269.png",
              ),
            ],
          ),
          Restaurant(
            name: "The Burger Barn",
            location: "Opebi, Lagos",
            rating: 4.5,
            reviewCount: 340,
            price: 1200,
            deliveryTime: "15 - 25 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 26912.png",
            openingHours: "9:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Classic Beef Burger",
                description:
                    "Juicy beef patty with lettuce, tomato, and cheese.",
                price: 1500,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
              MenuItem(
                name: "Chicken Burger",
                description: "Grilled chicken burger with mayo and pickles.",
                price: 1400,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
          Restaurant(
            name: "Owerri Soup House",
            location: "Alimosho, Lagos",
            rating: 4.3,
            reviewCount: 190,
            price: 650,
            deliveryTime: "30 - 40 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 26912.png",
            openingHours: "8:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Oha Soup",
                description:
                    "Traditional oha soup with goat meat and stockfish.",
                price: 800,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
              MenuItem(
                name: "Bitterleaf Soup",
                description: "Bitterleaf soup with assorted meat.",
                price: 750,
                isAvailable: false,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
          Restaurant(
            name: "The Sushi Spot",
            location: "VGC, Lagos",
            rating: 4.8,
            reviewCount: 420,
            price: 2500,
            deliveryTime: "20 - 30 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 2694.png",
            openingHours: "10:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "California Roll",
                description: "Sushi roll with crab, avocado, and cucumber.",
                price: 2000,
                isAvailable: true,
                imageUrl: "asset/images/Frame 2694.png",
              ),
              MenuItem(
                name: "Spicy Tuna Roll",
                description: "Sushi roll with spicy tuna and seaweed.",
                price: 2200,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
          Restaurant(
            name: "Aunty Esther’s Kitchen",
            location: "Egbeda, Lagos",
            rating: 4.1,
            reviewCount: 160,
            price: 500,
            deliveryTime: "25 - 35 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 26912.png",
            openingHours: "7:30 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Jollof Rice & Plantain",
                description:
                    "Spicy jollof rice with fried plantain and chicken.",
                price: 600,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
              MenuItem(
                name: "Vegetable Soup",
                description: "Rich vegetable soup with fish and ponmo.",
                price: 700,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
          Restaurant(
            name: "The Taco Stop",
            location: "Ilupeju, Lagos",
            rating: 4.4,
            reviewCount: 290,
            price: 1000,
            deliveryTime: "15 - 25 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 269.png",
            openingHours: "9:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Beef Taco",
                description: "Crispy taco with seasoned beef and salsa.",
                price: 1200,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
              MenuItem(
                name: "Chicken Taco",
                description: "Soft taco with grilled chicken and guacamole.",
                price: 1100,
                isAvailable: false,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
          Restaurant(
            name: "Iya Alaro’s Buka",
            location: "Ketu, Lagos",
            rating: 4.2,
            reviewCount: 140,
            price: 450,
            deliveryTime: "20 - 30 mins",
            isAvailable: true,
            imageUrl: "asset/images/Frame 269.png",
            openingHours: "7:00 PM",
            deliveryType: "Instant Delivery",
            menuItems: [
              MenuItem(
                name: "Amala & Gbegiri",
                description: "Smooth amala with gbegiri and ewedu soup.",
                price: 500,
                isAvailable: true,
                imageUrl: "asset/images/Frame 269.png",
              ),
              MenuItem(
                name: "Pounded Yam & Egusi",
                description: "Pounded yam with egusi stew and fish.",
                price: 600,
                isAvailable: true,
                imageUrl: "asset/images/Frame 26912.png",
              ),
            ],
          ),
        ]);

  void toggleFavorite(int index) {
    final updatedRestaurants = [...state];
    updatedRestaurants[index] = Restaurant(
      name: updatedRestaurants[index].name,
      location: updatedRestaurants[index].location,
      rating: updatedRestaurants[index].rating,
      reviewCount: updatedRestaurants[index].reviewCount,
      price: updatedRestaurants[index].price,
      deliveryTime: updatedRestaurants[index].deliveryTime,
      isAvailable: updatedRestaurants[index].isAvailable,
      imageUrl: updatedRestaurants[index].imageUrl,
      openingHours: updatedRestaurants[index].openingHours,
      deliveryType: updatedRestaurants[index].deliveryType,
      menuItems: updatedRestaurants[index].menuItems,
      isFavorite: !updatedRestaurants[index].isFavorite,
    );
    state = updatedRestaurants;
  }
}

final restaurantProvider =
    StateNotifierProvider<RestaurantNotifier, List<Restaurant>>((ref) {
  return RestaurantNotifier();
});
